spring:
  application:
    name: contacts-aggregator
  data:
    redis:
      database: 0
      host: localhost
      port: 16379
      password: local

springdoc:
  swagger-ui:
    path: /docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

rest-integrations:
  kenect-labs-api:
    base-url: ${KENECT_LABS_API_BASE_URL}
    token: ${KENECT_LABS_API_TOKEN}